const cardImg2x2 = [
	{ src: "/images/docker.png", matching: false },
	{ src: "/images/css.png", matching: false },
];

const cardImg4x4 = [
	{ src: "/images/android.png", matching: false },
	{ src: "/images/angular.png", matching: false },
	{ src: "/images/docker.png", matching: false },
	{ src: "/images/drupal.png", matching: false },
	{ src: "/images/github.png", matching: false },
	{ src: "/images/css.png", matching: false },
	{ src: "/images/git.png", matching: false },
	{ src: "/images/c.png", matching: false },
];

const cardImg6x6 = [
	{ src: "/images/javascript.png", matching: false },
	{ src: "/images/android.png", matching: false },
	{ src: "/images/angular.png", matching: false },
	{ src: "/images/msteams.png", matching: false },
	{ src: "/images/docker.png", matching: false },
	{ src: "/images/drupal.png", matching: false },
	{ src: "/images/github.png", matching: false },
	{ src: "/images/heroku.png", matching: false },
	{ src: "/images/linux.png", matching: false },
	{ src: "/images/mocha.png", matching: false },
	{ src: "/images/mongo.png", matching: false },
	{ src: "/images/mysql.png", matching: false },
	{ src: "/images/html.png", matching: false },
	{ src: "/images/java.png", matching: false },
	{ src: "/images/node.png", matching: false },
	{ src: "/images/css.png", matching: false },
	{ src: "/images/git.png", matching: false },
	{ src: "/images/c.png", matching: false },
];

const cardImg8x8 = [
	{ src: "/images/visualstudio.png", matching: false },
	{ src: "/images/javascript.png", matching: false },
	{ src: "/images/postgresql.png", matching: false },
	{ src: "/images/typescript.png", matching: false },
	{ src: "/images/android.png", matching: false },
	{ src: "/images/angular.png", matching: false },
	{ src: "/images/msteams.png", matching: false },
	{ src: "/images/paragon.png", matching: false },
	{ src: "/images/postman.png", matching: false },
	{ src: "/images/docker.png", matching: false },
	{ src: "/images/drupal.png", matching: false },
	{ src: "/images/github.png", matching: false },
	{ src: "/images/heroku.png", matching: false },
	{ src: "/images/python.png", matching: false },
	{ src: "/images/linux.png", matching: false },
	{ src: "/images/mocha.png", matching: false },
	{ src: "/images/mongo.png", matching: false },
	{ src: "/images/mysql.png", matching: false },
	{ src: "/images/react.png", matching: false },
	{ src: "/images/scala.png", matching: false },
	{ src: "/images/slack.png", matching: false },
	{ src: "/images/swift.png", matching: false },
	{ src: "/images/unity.png", matching: false },
	{ src: "/images/html.png", matching: false },
	{ src: "/images/java.png", matching: false },
	{ src: "/images/node.png", matching: false },
	{ src: "/images/rail.png", matching: false },
	{ src: "/images/css.png", matching: false },
	{ src: "/images/git.png", matching: false },
	{ src: "/images/vue.png", matching: false },
	{ src: "/images/go.png", matching: false },
	{ src: "/images/c.png", matching: false },
];

export { cardImg2x2, cardImg4x4, cardImg6x6, cardImg8x8 };
